### ISSUE TITLE
[Bug]: player.equipItem, player.equipItemEx, and player.sheatheWeapon freezes the game if player has hand or weapon drawn

### ISSUE THREAD

**Issue by rzkyif** [skyrim-multiplayer/skymp#706]
### Severity

Major. A crucial error that indicates a deviation from business logic or disrupts the program, but doesn't have a vital impact on the app.

### Priority

Medium. Anything that negatively affects the user experience.

### Description

Hello! I'm the author of the [rykz's Item Menu](https://www.nexusmods.com/skyrimspecialedition/mods/59701) plugin up on Nexus. I faced the problem written on the title and thought you guys might want to know and warn other plugin devs about it:

1. When you call `Actor.equipItem` or `Actor.equipItemEx` on the player character, the related item is of the type `Weapon`, and the player has their hand or weapon drawn, the game freezes without crashing.
2. If you try to call `Actor.sheatheWeapon` on the player character before that, the game also freezes without crashing.

I suspect this is related to #653, but I can't really confirm this.

Temporary workaround that I currently use is to just not call `player.equipItem` and `player.equipItemEx` if `player.isWeaponDrawn` returns `true`.

### OS

Windows

### OS version

10

### Skyrim version

1.5.97

### SKSE version

2.0.20

### client commit''s hash

eaba5284460a1e4bdf676b88806a337555e2a9f8

### server commit''s hash

N/A

### Videocard model

Geforce GTX 1050 Ti

### Steps to reproduce

My code that causes this issue is this (with some lines removed for brevity):
```ts
function queueItem(actionType: number, itemId: number, itemCount: number) {
  once("update", () => {
    ...
    switch (actionType) {
      ...
      case 1: // EQUIP
        if (player.isEquipped(item)) {
          ...
        } else {
          ...
          player.equipItemEx(
            item,
            0,
            false,
            true
          );
          ...
        }
        break;
    }
  });
}
```
The `queueItem` function is called in a callback for a `browserMessage` event. 

If anyone wants to quickly test this, this bug is "included" in the [1.2.0 version of my plugin](https://www.nexusmods.com/skyrimspecialedition/mods/59701?tab=files&file_id=250048). After installing that plugin, you can then put your hands out by clicking left click or R, open my menu by pressing O, type "steel greatsword", then right click the topmost Steel Greatsword search result to equip them (while your hands are out). The game should freeze right after you right click the search result.

### Expected result

Player equips the item safely after unequipping the previous item.

### Actual result

If player has their hand or weapon drawn, and item's `FormType` is `FormType.Weapon`, the game freezes but doesn't crash. 

No crash logs are generated since the game doesn't crash, and I tried checking the Papyrus log but there's nothing related to this problem there.

**Comment by Pospelove** [comment]
Thanks for posting detailed bug report!

**Comment by Pospelove** [comment]
probably fixed in the coming 2.6.

**Comment by Y3sMan** [comment]
I hate to dredge this back up but in 2.6 I'm still having this problem with "equipSpell." Freezes still occur when weapons are drawn and I try to run "equipSpell."
